### ISSUE TITLE
Theme not supported in latest version of PyCharm 

### ISSUE THREAD

**Issue by lucianosrp** [kristijanribaric/ayu-dark-jetbrains#2]
The theme is imcompatible as of PyCharm `2024.2`
![image](https://github.com/user-attachments/assets/538ea7f4-aafc-43f1-b5b8-9a3f47df32af)

**Comment by kristijanribaric** [comment]
Thank you for raising the issue! I will update it today.

**Comment by kristijanribaric** [comment]
The plugin has been updated. Try to update it in your IDE and close the issue if it works.

**Comment by lucianosrp** [comment]
Thanks again for the prompt response! 
I can confirm that the theme now works.
